### ISSUE TITLE
TypeError: make() missing 1 required positional argument: 'arg2'

### ISSUE THREAD

**Issue by alphafox02** [proto17/dji_droneid#11]
Good evening. I switched from the gnuradio branch to the new gnuradio branch, uninstalled and then installed the latest. 

While performing a quick test (on same machine the older gnuradio flowgraph ran on) I now encounter this upon starting and wondered if it's just me or if anyone else is having this issue,

`[INFO] [B200] Detected Device: B205mini
[INFO] [B200] Operating over USB 3.
[INFO] [B200] Initialize CODEC control...
[INFO] [B200] Initialize Radio control...
[INFO] [B200] Performing register loopback test... 
[INFO] [B200] Register loopback test passed
[INFO] [B200] Setting master clock rate selection to 'automatic'.
[INFO] [B200] Asking for clock rate 16.000000 MHz... 
[INFO] [B200] Actually got clock rate 16.000000 MHz.
[INFO] [B200] Asking for clock rate 30.720000 MHz... 
[INFO] [B200] Actually got clock rate 30.720000 MHz.
[INFO] [MULTI_USRP]     1) catch time transition at pps edge
[INFO] [MULTI_USRP]     2) set times next pps (synchronously)
Traceback (most recent call last):
  File "/tmp/drone_id_demod_test.py", line 357, in <module>
    main()
  File "/tmp/drone_id_demod_test.py", line 335, in main
    tb = top_block_cls()
  File "/tmp/drone_id_demod_test.py", line 222, in __init__
    self.droneid_extractor_0 = droneid.extractor(samp_rate / decimation, )
TypeError: make() missing 1 required positional argument: 'arg2'

>>> Done (return code 1)
`

**Comment by alphafox02** [comment]
I uninstalled gr-droneid update branch, went back to just the gr-droneid branch and all is well after making the /tmp/bursts directory. Not sure what's causing the difference in the update branch.

**Comment by alphafox02** [comment]
No red that I can see, graph builds, but maybe somehow there’s a missing variable even though the blocks are not red.

**Comment by alphafox02** [comment]
Looks like arg2 should be a float. When looking at the generated .py file there’s nothing after the , so no arg2 that is. Just seeing what might be expected there.

**Comment by alphafox02** [comment]
Got it, the extractor on the flow graph had no correlator value, but then again no red. I put a zero in and the flow graph will run now.
